[package]
name = "html_to_markdown_elixir"
version ="2.22.5"
edition = "2024"
license = "MIT"
description = "Rustler bindings for html-to-markdown"
repository = "https://github.com/kreuzberg-dev/html-to-markdown"

[lib]
name = "html_to_markdown_elixir"
crate-type = ["cdylib"]

[dependencies]
html-to-markdown-rs = { path = "vendor/html-to-markdown-rs", features = ["inline-images", "metadata"] }
rustler = { version = "0.37" }

[target.'cfg(not(target_os = "windows"))'.dependencies]
pprof = { version = "0.15", features = ["flamegraph"], optional = true }

[features]
default = []
profiling = ["dep:pprof"]
